project:
  type: website

website:
  favicon: "favicon.ico"
  site-url: "http://sharleenw.rbind.io"
  search: FALSE
  navbar:
    left:
      - text: "Home"
        file: "index.qmd"
      - about.qmd
      - icon: github
        href: https://github.com/sharleenw
format:
  html:
    theme: minty
    css: styles.css

editor: visual

